// ============================================================
// DADOS MOCK — simula respostas da API Spring Boot
// ============================================================

export const mockUsuarios = [
  {
    id: 1,
    nome_completo: 'Admin Sistema',
    cpf: '123.456.789-09',
    data_nascimento: '1990-03-15',
    telefone: '(11) 99999-0001',
    email: 'admin@rental.com',
    endereco: 'Rua das Flores, 100 — São Paulo/SP',
    tipo: 'admin',
    senha: 'admin123',
  },
  {
    id: 2,
    nome_completo: 'Carlos Eduardo Santos',
    cpf: '987.654.321-00',
    data_nascimento: '1995-07-22',
    telefone: '(21) 98888-0002',
    email: 'cliente@rental.com',
    endereco: 'Av. Atlântica, 500 — Rio de Janeiro/RJ',
    tipo: 'cliente',
    senha: 'cliente123',
  },
  {
    id: 3,
    nome_completo: 'Mariana Oliveira Costa',
    cpf: '456.789.123-87',
    data_nascimento: '1988-11-04',
    telefone: '(31) 97777-0003',
    email: 'mariana@email.com',
    endereco: 'Rua Savassi, 200 — Belo Horizonte/MG',
    tipo: 'cliente',
    senha: 'maria123',
  },
  {
    id: 4,
    nome_completo: 'João Paulo Ferreira',
    cpf: '321.654.987-12',
    data_nascimento: '1992-05-18',
    telefone: '(47) 96666-0004',
    email: 'joao@email.com',
    endereco: 'Rua XV de Novembro, 800 — Joinville/SC',
    tipo: 'cliente',
    senha: 'joao123',
  },
];

export const mockVeiculos = [
  {
    id: 1,
    modelo: 'Onix Plus',
    cor: 'Prata',
    fabricante: 'Chevrolet',
    placa: 'BRA2E19',
    disponivel: 1,
    categoria: 'Econômico',
    ano: 2023,
    cambio: 'Automático',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 129.90,
    km: 12400,
    imagem: null,
  },
  {
    id: 2,
    modelo: 'Compass Longitude',
    cor: 'Branco',
    fabricante: 'Jeep',
    placa: 'ABC1D23',
    disponivel: 0,
    categoria: 'SUV',
    ano: 2024,
    cambio: 'Automático',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 289.90,
    km: 8200,
    imagem: null,
  },
  {
    id: 3,
    modelo: 'HB20 Sense',
    cor: 'Vermelho',
    fabricante: 'Hyundai',
    placa: 'MER3F45',
    disponivel: 1,
    categoria: 'Econômico',
    ano: 2022,
    cambio: 'Manual',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 99.90,
    km: 31500,
    imagem: null,
  },
  {
    id: 4,
    modelo: 'Hilux CD SRX',
    cor: 'Cinza',
    fabricante: 'Toyota',
    placa: 'TOY4G56',
    disponivel: 1,
    categoria: 'Picape',
    ano: 2024,
    cambio: 'Automático',
    combustivel: 'Diesel',
    portas: 4,
    passageiros: 5,
    valor_diaria: 399.90,
    km: 5100,
    imagem: null,
  },
  {
    id: 5,
    modelo: 'Pulse Drive',
    cor: 'Azul',
    fabricante: 'Fiat',
    placa: 'FIA5H67',
    disponivel: 1,
    categoria: 'SUV',
    ano: 2023,
    cambio: 'CVT',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 199.90,
    km: 18700,
    imagem: null,
  },
  {
    id: 6,
    modelo: 'Corolla Altis',
    cor: 'Preto',
    fabricante: 'Toyota',
    placa: 'TOY6I78',
    disponivel: 0,
    categoria: 'Sedan',
    ano: 2024,
    cambio: 'Automático',
    combustivel: 'Híbrido',
    portas: 4,
    passageiros: 5,
    valor_diaria: 359.90,
    km: 3300,
    imagem: null,
  },
  {
    id: 7,
    modelo: 'Kwid Zen',
    cor: 'Laranja',
    fabricante: 'Renault',
    placa: 'REN7J89',
    disponivel: 1,
    categoria: 'Econômico',
    ano: 2022,
    cambio: 'Manual',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 79.90,
    km: 44200,
    imagem: null,
  },
  {
    id: 8,
    modelo: 'EcoSport Storm',
    cor: 'Verde',
    fabricante: 'Ford',
    placa: 'FOR8K90',
    disponivel: 1,
    categoria: 'SUV',
    ano: 2023,
    cambio: 'Automático',
    combustivel: 'Flex',
    portas: 4,
    passageiros: 5,
    valor_diaria: 249.90,
    km: 21600,
    imagem: null,
  },
];

export const mockAlugueis = [
  {
    id: 1,
    data_retirada: '2025-05-10',
    data_entrega: '2025-05-15',
    forma_pagamento: 'cartao_credito',
    status: 'finalizado',
    finalizado_em: '2025-05-15T14:30:00',
    usuario_id: 2,
    veiculo_id: 1,
    usuario: 'Carlos Eduardo Santos',
    veiculo: 'Onix Plus',
    placa: 'BRA2E19',
    valor_total: 649.50,
  },
  {
    id: 2,
    data_retirada: '2025-06-01',
    data_entrega: '2025-06-07',
    forma_pagamento: 'pix',
    status: 'ativo',
    finalizado_em: null,
    usuario_id: 3,
    veiculo_id: 2,
    usuario: 'Mariana Oliveira Costa',
    veiculo: 'Compass Longitude',
    placa: 'ABC1D23',
    valor_total: 2029.30,
  },
  {
    id: 3,
    data_retirada: '2025-05-20',
    data_entrega: '2025-05-22',
    forma_pagamento: 'dinheiro',
    status: 'finalizado',
    finalizado_em: '2025-05-22T09:00:00',
    usuario_id: 4,
    veiculo_id: 3,
    usuario: 'João Paulo Ferreira',
    veiculo: 'HB20 Sense',
    placa: 'MER3F45',
    valor_total: 199.80,
  },
  {
    id: 4,
    data_retirada: '2025-06-05',
    data_entrega: '2025-06-12',
    forma_pagamento: 'cartao_debito',
    status: 'ativo',
    finalizado_em: null,
    usuario_id: 2,
    veiculo_id: 6,
    usuario: 'Carlos Eduardo Santos',
    veiculo: 'Corolla Altis',
    placa: 'TOY6I78',
    valor_total: 2519.30,
  },
];
